# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2439addca5292981c5a5becbf452f1a762d64b56407a450f6f1be2bdda9d766749ec8a8a67cebd53462147cda74e1ba357d8cc3db95267ad860606aa9a9c28f6

test:
  secret_key_base: 786d8e0e20fd583fd196d2810e5a824ff017981a5a773c1f8c554e0ba972dca863e566b66eabdf3b634912eba2540262d25df7383ea52e678d786d6e3acf4dc1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
